/* SPDX-FileCopyrightText: 2025 JPShag
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "NetPrivacyJob.h"

#include <libcalamares/GlobalStorage.h>
#include <libcalamares/JobQueue.h>
#include <libcalamares/utils/Logger.h>

#include <QDir>
#include <QFile>
#include <QRegularExpression>
#include <QSaveFile>
#include <QTextStream>

NetPrivacyJob::NetPrivacyJob( int macPolicy,
                              const QString& macAddress,
                              const QString& vendorOUI,
                              bool ipv6Privacy,
                              int ipv6Mode,
                              QObject* parent )
    : Calamares::CppJob( parent )
    , m_macPolicy( macPolicy )
    , m_macAddress( macAddress )
    , m_vendorOUI( vendorOUI )
    , m_ipv6Privacy( ipv6Privacy )
    , m_ipv6Mode( ipv6Mode )
{
}

NetPrivacyJob::~NetPrivacyJob() {}

QString NetPrivacyJob::prettyName() const { return tr( "Configure Network Privacy" ); }
QString NetPrivacyJob::prettyDescription() const { return tr( "Configuring MAC and IPv6 privacy settings..." ); }
QString NetPrivacyJob::prettyStatusMessage() const { return tr( "Writing network privacy configuration..." ); }

Calamares::JobResult
NetPrivacyJob::exec()
{
    // Validate OUI format to prevent shell injection
    if ( !m_vendorOUI.isEmpty() )
    {
        static const QRegularExpression ouiRegex( "^[0-9a-fA-F]{2}:[0-9a-fA-F]{2}:[0-9a-fA-F]{2}$" );
        if ( !ouiRegex.match( m_vendorOUI ).hasMatch() )
        {
            return Calamares::JobResult::error( tr( "Security Error" ), 
                                                tr( "Invalid Vendor OUI format for network privacy. Aborting." ) );
        }
    }

    auto* gs = Calamares::JobQueue::instance()->globalStorage();
    if ( !gs )
        return Calamares::JobResult::internalError( tr( "Error" ), tr( "No GlobalStorage available." ), 1 );

    QString root = gs->value( QStringLiteral( "rootMountPoint" ) ).toString();
    if ( root.isEmpty() )
        return Calamares::JobResult::internalError( tr( "Error" ), tr( "Root mount point not set." ), 1 );

    cDebug() << "NetPrivacyJob: root=" << root << "macPolicy=" << m_macPolicy << "ipv6Mode=" << m_ipv6Mode;

    if ( m_macPolicy > 0 )
    {
        auto r = writeMacConfig( root );
        if ( !r ) return r;
        writeSystemdLinkConfig( root );
    }

    if ( m_ipv6Mode != 0 )
    {
        auto r = writeIpv6Config( root );
        if ( !r ) return r;
    }

    return Calamares::JobResult::ok();
}

Calamares::JobResult
NetPrivacyJob::writeMacConfig( const QString& root ) const
{
    // Use /etc for local configuration
    const QString confDir = root + QStringLiteral( "/etc/NetworkManager/conf.d" );
    
    // Check if NetworkManager is installed (check both lib and sbin)
    bool nmInstalled = QDir( root + "/usr/lib/NetworkManager" ).exists() || 
                       QDir( root + "/usr/sbin/NetworkManager" ).exists();

    if ( !nmInstalled )
    {
        cWarning() << "NetPrivacyJob: NetworkManager not detected, skipping MAC config";
        return Calamares::JobResult::ok();
    }

    if ( !QDir().mkpath( confDir ) )
        return Calamares::JobResult::error( tr( "Error" ), tr( "Cannot create: %1" ).arg( confDir ) );

    const QString confPath = confDir + QStringLiteral( "/80-calamares-mac-privacy.conf" );
    QString content;
    QTextStream s( &content );
    s << "# Generated by Calamares netprivacy module\n\n";

    switch ( m_macPolicy )
    {
    case 1: // Random
        s << "[device]\nwifi.scan-rand-mac-address=yes\n\n";
        s << "[connection]\nwifi.cloned-mac-address=random\nethernet.cloned-mac-address=random\n";
        break;
    case 2: // Vendor/Stable
        s << "[device]\nwifi.scan-rand-mac-address=yes\n\n";
        s << "[connection]\nwifi.cloned-mac-address=stable\nethernet.cloned-mac-address=stable\n";
        break;
    case 3: // Fixed
        if ( m_macAddress.isEmpty() )
            return Calamares::JobResult::error( tr( "Error" ), tr( "No MAC address provided." ) );
        s << "[connection]\nwifi.cloned-mac-address=" << m_macAddress << "\n";
        s << "ethernet.cloned-mac-address=" << m_macAddress << "\n";
        break;
    default:
        return Calamares::JobResult::ok();
    }

    if ( !writeFile( confPath, content ) )
        return Calamares::JobResult::error( tr( "Error" ), tr( "Cannot write: %1" ).arg( confPath ) );

    cDebug() << "NetPrivacyJob: Wrote" << confPath;

    // Vendor dispatcher script
    if ( m_macPolicy == 2 && !m_vendorOUI.isEmpty() )
    {
        const QString dispDir = root + QStringLiteral( "/etc/NetworkManager/dispatcher.d" );
        if ( QDir().mkpath( dispDir ) )
        {
            const QString dispPath = dispDir + QStringLiteral( "/80-vendor-mac.sh" );
            QString script;
            QTextStream ds( &script );
            ds << "#!/bin/bash\n";
            ds << "# Vendor MAC enforcement\n";
            ds << "set -euo pipefail\n\n";
            // Security: Use single quotes for OUI to prevent expansion
            ds << "VENDOR_OUI='" << m_vendorOUI.toLower() << "'\n";
            ds << "IFACE=\"${1:-}\"\n";
            ds << "ACTION=\"${2:-}\"\n\n";
            ds << "[[ \"$ACTION\" == \"up\" ]] || exit 0\n";
            // Ignore loopback, veth, docker
            ds << "[[ \"$IFACE\" == \"lo\" || \"$IFACE\" == veth* || \"$IFACE\" == docker* ]] && exit 0\n\n";
            // Safe read using < process substitution to avoid pipe issues
            ds << "read -r CURRENT < <(ip link show dev \"$IFACE\" 2>/dev/null | awk '/ether/ {print tolower($2)}')\n";
            ds << "[[ \"${CURRENT:0:8}\" == \"$VENDOR_OUI\" ]] && exit 0\n\n";
            
            ds << "NIC=$(printf '%02x:%02x:%02x' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))\n";
            ds << "NEW=\"${VENDOR_OUI}:${NIC}\"\n\n";
            ds << "ip link set dev \"$IFACE\" down 2>/dev/null || true\n";
            ds << "ip link set dev \"$IFACE\" address \"$NEW\"\n";
            ds << "ip link set dev \"$IFACE\" up\n";
            ds << "logger -t netprivacy \"[$IFACE] MAC=$NEW\"\n";

            if ( writeFile( dispPath, script ) )
            {
                QFile::setPermissions( dispPath,
                    QFileDevice::ReadOwner | QFileDevice::WriteOwner | QFileDevice::ExeOwner |
                    QFileDevice::ReadGroup | QFileDevice::ExeGroup |
                    QFileDevice::ReadOther | QFileDevice::ExeOther );
                cDebug() << "NetPrivacyJob: Wrote" << dispPath;
            }
        }
    }

    return Calamares::JobResult::ok();
}

Calamares::JobResult
NetPrivacyJob::writeSystemdLinkConfig( const QString& root ) const
{
    // Use /etc/systemd/network
    const QString linkDir = root + QStringLiteral( "/etc/systemd/network" );

    if ( !QDir( root + "/usr/lib/systemd" ).exists() )
    {
        cWarning() << "NetPrivacyJob: systemd not detected, skipping .link config";
        return Calamares::JobResult::ok();
    }

    if ( !QDir().mkpath( linkDir ) )
    {
        cWarning() << "NetPrivacyJob: Cannot create" << linkDir;
        return Calamares::JobResult::ok();
    }

    const QString linkPath = linkDir + QStringLiteral( "/80-calamares-mac-privacy.link" );
    QString content;
    QTextStream s( &content );
    s << "# Generated by Calamares netprivacy module\n\n";
    s << "[Match]\nOriginalName=*\n\n[Link]\n";

    switch ( m_macPolicy )
    {
    case 1:
    case 2:
        s << "MACAddressPolicy=random\n";
        break;
    case 3:
        s << "MACAddress=" << m_macAddress << "\n";
        break;
    }

    if ( writeFile( linkPath, content ) )
        cDebug() << "NetPrivacyJob: Wrote" << linkPath;

    return Calamares::JobResult::ok();
}

Calamares::JobResult
NetPrivacyJob::writeIpv6Config( const QString& root ) const
{
    if ( m_ipv6Mode == 2 )
    {
        // Use /etc/sysctl.d/
        const QString sysctlDir = root + QStringLiteral( "/etc/sysctl.d" );
        if ( !QDir().mkpath( sysctlDir ) )
            return Calamares::JobResult::error( tr( "Error" ), tr( "Cannot create: %1" ).arg( sysctlDir ) );

        const QString sysctlPath = sysctlDir + QStringLiteral( "/99-calamares-disable-ipv6.conf" );
        QString content;
        QTextStream s( &content );
        s << "# Generated by Calamares netprivacy module\n";
        s << "net.ipv6.conf.all.disable_ipv6 = 1\n";
        s << "net.ipv6.conf.default.disable_ipv6 = 1\n";
        s << "net.ipv6.conf.lo.disable_ipv6 = 1\n";

        if ( !writeFile( sysctlPath, content ) )
            return Calamares::JobResult::error( tr( "Error" ), tr( "Cannot write: %1" ).arg( sysctlPath ) );

        cDebug() << "NetPrivacyJob: Wrote" << sysctlPath;
    }
    else if ( m_ipv6Mode == 1 )
    {
        // IPv6 privacy extensions for NetworkManager
        // Use /etc/NetworkManager/conf.d
        const QString nmDir = root + QStringLiteral( "/etc/NetworkManager/conf.d" );
        
        bool nmInstalled = QDir( root + "/usr/lib/NetworkManager" ).exists() || 
                           QDir( root + "/usr/sbin/NetworkManager" ).exists();
                           
        if ( nmInstalled && QDir().mkpath( nmDir ) )
        {
            const QString nmPath = nmDir + QStringLiteral( "/80-calamares-ipv6-privacy.conf" );
            QString nmContent;
            QTextStream s1( &nmContent );
            s1 << "# Generated by Calamares netprivacy module\n\n";
            s1 << "[connection]\nipv6.ip6-privacy=2\n";

            if ( writeFile( nmPath, nmContent ) )
                cDebug() << "NetPrivacyJob: Wrote" << nmPath;
        }

        // systemd-networkd config
        // Use /etc/systemd/networkd.conf.d
        const QString networkdDir = root + QStringLiteral( "/etc/systemd/networkd.conf.d" );
        if ( QDir( root + "/usr/lib/systemd" ).exists() && QDir().mkpath( networkdDir ) )
        {
            const QString networkdPath = networkdDir + QStringLiteral( "/80_ipv6-privacy-extensions.conf" );
            QString networkdContent;
            QTextStream s2( &networkdContent );
            s2 << "# Generated by Calamares netprivacy module\n\n";
            s2 << "[Network]\nIPv6PrivacyExtensions=kernel\n";

            if ( writeFile( networkdPath, networkdContent ) )
                cDebug() << "NetPrivacyJob: Wrote" << networkdPath;
        }
    }

    return Calamares::JobResult::ok();
}

bool
NetPrivacyJob::writeFile( const QString& path, const QString& content ) const
{
    QSaveFile file( path );
    if ( !file.open( QIODevice::WriteOnly | QIODevice::Text ) )
    {
        cWarning() << "NetPrivacyJob: Cannot open" << path << file.errorString();
        return false;
    }

    QTextStream s( &file );
    s << content;

    if ( !file.commit() )
    {
        cWarning() << "NetPrivacyJob: Cannot commit" << path << file.errorString();
        return false;
    }

    QFile::setPermissions( path,
        QFileDevice::ReadOwner | QFileDevice::WriteOwner |
        QFileDevice::ReadGroup | QFileDevice::ReadOther );

    return true;
}
